import express from "express"; // WHY: Import Express to create REST endpoints for bridge operations.
import { Connection, Keypair, PublicKey, Transaction, SystemProgram, SYSVAR_RENT_PUBKEY } from "@solana/web3.js"; // WHY: Import Solana web3 classes for building and sending transactions.
import { AnchorProvider, Program, Wallet, BN } from "@coral-xyz/anchor"; // WHY: Import Anchor utilities to interact with on-chain programs using an IDL.
import { getAssociatedTokenAddressSync, TOKEN_PROGRAM_ID } from "@solana/spl-token"; // WHY: Import SPL token helpers to derive token account addresses synchronously.
import { createHash } from "crypto"; // WHY: Import Node crypto to compute SHA-256 message digests that guardians sign.
import fs from "fs"; // WHY: Import filesystem module to read program IDLs and wallet keypairs from disk.
import path from "path"; // WHY: Import path module to resolve file locations across operating systems.

const app = express(); // WHY: Instantiate the Express application to register routes and middleware.
app.use(express.json()); // WHY: Parse JSON request bodies so instruction parameters are available as JavaScript objects.

const RPC_URL = process.env.SOLANA_RPC || "http://127.0.0.1:8899"; // WHY: Allow environment override so the same API works on devnet and local validator.
const connection = new Connection(RPC_URL, "confirmed"); // WHY: Establish a connection with confirmed commitment to ensure reads reflect finalized state.

const walletPath = process.env.WALLET || path.join(process.env.HOME || "", ".config/solana/id.json"); // WHY: Resolve the payer wallet path from environment or default Solana CLI location.
const keypair = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(fs.readFileSync(walletPath, "utf8")))); // WHY: Load the payer's secret key so the API can sign and pay for transactions.
const wallet = new Wallet(keypair); // WHY: Wrap the keypair in Anchor's Wallet interface for Provider compatibility.
const provider = new AnchorProvider(connection, wallet, { commitment: "confirmed" }); // WHY: Create a provider that links the connection and signer to all program interactions.

const bridgeIdlPath = path.join(__dirname, "bridge", "target", "idl", "bridge.json"); // WHY: Resolve the bridge program IDL generated by Anchor build.
const bridgeIdl = JSON.parse(fs.readFileSync(bridgeIdlPath, "utf8")); // WHY: Parse the IDL into a JavaScript object for typed program instantiation.
const bridgeProgramId = new PublicKey(bridgeIdl.address); // WHY: Extract the on-chain program address from the IDL metadata.
const bridgeProgram = new Program(bridgeIdl, bridgeProgramId, provider); // WHY: Create a typed Program instance to build bridge instructions.

const guardianIdlPath = path.join(__dirname, "bridge", "target", "idl", "guardian.json"); // WHY: Resolve the guardian program IDL generated by Anchor build.
const guardianIdl = JSON.parse(fs.readFileSync(guardianIdlPath, "utf8")); // WHY: Parse the IDL into a JavaScript object for typed program instantiation.
const guardianProgramId = new PublicKey(guardianIdl.address); // WHY: Extract the on-chain program address from the IDL metadata.
const guardianProgram = new Program(guardianIdl, guardianProgramId, provider); // WHY: Create a typed Program instance to build guardian instructions.

const getBridgeStatePDA = () => { // WHY: Define a helper to deterministically compute the bridge state account address.
  return PublicKey.findProgramAddressSync([Buffer.from("bridge_state")], bridgeProgramId)[0]; // WHY: Use the same seed as the Rust program so TypeScript and on-chain derivations match.
}; // WHY: Close the helper function scope.

const getVaultPDA = (bridgeState: PublicKey) => { // WHY: Define a helper to compute the vault PDA which depends on the state address.
  return PublicKey.findProgramAddressSync([Buffer.from("vault"), bridgeState.toBuffer()], bridgeProgramId)[0]; // WHY: Replicate the Rust seed derivation exactly to avoid address mismatches.
}; // WHY: Close the helper function scope.

const getGuardianRegistryPDA = () => { // WHY: Define a helper to compute the guardian registry account address.
  return PublicKey.findProgramAddressSync([Buffer.from("guardian_registry")], guardianProgramId)[0]; // WHY: Use the same seed as the Rust guardian program for consistent addressing.
}; // WHY: Close the helper function scope.

app.post("/lock", async (req, res) => { // WHY: Register an endpoint for users to lock original tokens into the bridge vault.
  try { // WHY: Open a try block so validation or RPC errors return HTTP 500 with details instead of crashing the process.
    const { userSecretKey, amount, originalMint } = req.body; // WHY: Destructure request fields: user's key, amount, and the original token mint.
    const userKp = Keypair.fromSecretKey(Uint8Array.from(userSecretKey)); // WHY: Reconstruct the user's keypair from the provided secret key bytes to sign the lock transaction.
    const userPubkey = userKp.publicKey; // WHY: Cache the user's public key for account derivation and transaction building.
    const originalMintPubkey = new PublicKey(originalMint); // WHY: Convert the string mint address into a typed PublicKey for account validation.
    const bridgeState = getBridgeStatePDA(); // WHY: Derive the bridge state address so the transaction references the correct account.
    const vault = getVaultPDA(bridgeState); // WHY: Derive the vault address that will receive the locked tokens.
    const userTokenAccount = getAssociatedTokenAddressSync(originalMintPubkey, userPubkey); // WHY: Derive the user's associated token account for the original mint.
    const stateData = await bridgeProgram.account.bridgeState.fetch(bridgeState); // WHY: Fetch the current on-chain nonce to build the lock record PDA seed.
    const lockRecordSeed = new BN(stateData.nonce.toString()).toArrayLike(Buffer, "le", 8); // WHY: Convert the current nonce to an 8-byte little-endian buffer matching the Rust seed.
    const lockRecord = PublicKey.findProgramAddressSync([Buffer.from("lock_record"), lockRecordSeed], bridgeProgramId)[0]; // WHY: Derive the lock record address using the current nonce as a unique seed.
    const tx = await bridgeProgram.methods // WHY: Start building the Anchor instruction using typed method names from the IDL.
      .lockTokens(new BN(amount)) // WHY: Convert the amount to a BN because Anchor expects big-number types for u64 fields.
      .accounts({ // WHY: Explicitly map every account the instruction expects so Anchor does not guess.
        user: userPubkey, // WHY: Pass the user's pubkey as the signer who owns the source tokens.
        bridgeState, // WHY: Pass the derived bridge state so the program can read the nonce and update it.
        userTokenAccount, // WHY: Pass the user's token account as the source of the transfer.
        vault, // WHY: Pass the vault as the destination for the locked original tokens.
        lockRecord, // WHY: Pass the derived lock record so the program can store deposit metadata.
        tokenProgram: TOKEN_PROGRAM_ID, // WHY: Specify the SPL Token program for the cross-program transfer invocation.
        systemProgram: SystemProgram.programId, // WHY: Specify the system program because lock record creation allocates rent space.
        rent: SYSVAR_RENT_PUBKEY, // WHY: Pass the rent sysvar because init accounts need rent exemption calculation.
      }) // WHY: Close the accounts mapping.
      .transaction(); // WHY: Build the transaction object without signing so we can add the user signer next.
    tx.feePayer = wallet.publicKey; // WHY: Set the API wallet as the fee payer so the user does not need SOL in a separate faucet step.
    tx.recentBlockhash = (await connection.getLatestBlockhash()).blockhash; // WHY: Fetch a recent blockhash so the transaction is valid for the current network slot.
    tx.partialSign(userKp); // WHY: Have the user sign first because they authorize the token transfer from their account.
    tx.partialSign(wallet.payer); // WHY: Have the API wallet sign to pay fees and satisfy the Anchor provider expectation.
    const sig = await connection.sendRawTransaction(tx.serialize()); // WHY: Serialize and send the fully signed transaction to the Solana cluster.
    await connection.confirmTransaction(sig, "confirmed"); // WHY: Wait for confirmation so the HTTP response reflects on-chain success.
    res.json({ success: true, signature: sig }); // WHY: Return the transaction signature so the client can track the lock on-chain.
  } catch (err) { // WHY: Catch any error from RPC, validation, or serialization.
    res.status(500).json({ error: String(err) }); // WHY: Return the error as JSON so the client can diagnose failed locks.
  } // WHY: Close the try block.
}); // WHY: Close the /lock route handler.

app.post("/mint", async (req, res) => { // WHY: Register an endpoint that accepts guardian signatures and triggers wrapped token minting.
  try { // WHY: Open a try block to catch validation or RPC errors during the mint flow.
    const { lockNonce, signatures, guardianIndices } = req.body; // WHY: Extract the lock nonce, Ed25519 signatures, and guardian index mappings from the request.
    const bridgeState = getBridgeStatePDA(); // WHY: Derive the bridge state address for the mint instruction accounts.
    const lockRecordSeed = new BN(lockNonce).toArrayLike(Buffer, "le", 8); // WHY: Convert the nonce to an 8-byte little-endian buffer to match the Rust seed derivation.
    const lockRecord = PublicKey.findProgramAddressSync([Buffer.from("lock_record"), lockRecordSeed], bridgeProgramId)[0]; // WHY: Derive the exact lock record address that corresponds to the deposit being minted against.
    const lockData = await bridgeProgram.account.lockRecord.fetch(lockRecord); // WHY: Fetch the lock record from chain to read the user and amount for the mint.
    const wrappedMint = await bridgeProgram.account.bridgeState.fetch(bridgeState).then((s: any) => s.wrappedMint); // WHY: Read the wrapped mint address from bridge state so the API targets the correct token.
    const recipientWrappedAccount = getAssociatedTokenAddressSync(wrappedMint, lockData.user); // WHY: Derive the user's wrapped token account to receive the newly minted tokens.
    const guardianRegistry = getGuardianRegistryPDA(); // WHY: Derive the guardian registry address so the program can verify signature pubkeys on-chain.
    const message = Buffer.concat([lockData.user.toBuffer(), new BN(lockData.amount.toString()).toArrayLike(Buffer, "le", 8), lockRecordSeed]); // WHY: Reconstruct the exact message bytes that guardians signed: user + amount + nonce.
    const messageHash = createHash("sha256").update(message).digest(); // WHY: Compute the SHA-256 digest so it can be compared against the on-chain verification input.
    const sigs = signatures.map((s: string) => Uint8Array.from(Buffer.from(s, "base64"))); // WHY: Decode base64-encoded signatures back into raw bytes for the transaction.
    const indices = guardianIndices.map((i: number) => i); // WHY: Copy guardian indices into a plain array for the Anchor instruction argument.
    const tx = await bridgeProgram.methods // WHY: Start building the typed Anchor instruction for verify_and_mint_wrapped.
      .verifyAndMintWrapped(Array.from(messageHash), sigs, indices) // WHY: Pass the message hash, signatures, and indices as typed arguments to the program.
      .accounts({ // WHY: Map every account expected by the verify_and_mint_wrapped instruction.
        bridgeState, // WHY: Pass the bridge state for threshold checks and nonce validation.
        lockRecord, // WHY: Pass the lock record to enforce single minting and read the locked amount.
        wrappedMint, // WHY: Pass the wrapped mint so the SPL program knows which supply to increase.
        recipientWrappedAccount, // WHY: Pass the user's wrapped account as the mint destination.
        guardianRegistry, // WHY: Pass the registry so the program can load guardian pubkeys and active status.
        tokenProgram: TOKEN_PROGRAM_ID, // WHY: Specify the SPL Token program for the mint CPI.
      }) // WHY: Close the accounts mapping.
      .transaction(); // WHY: Build the transaction object for multi-signer handling.
    tx.feePayer = wallet.publicKey; // WHY: Set the API wallet as the fee payer.
    tx.recentBlockhash = (await connection.getLatestBlockhash()).blockhash; // WHY: Fetch a recent blockhash for network validity.
    tx.partialSign(wallet.payer); // WHY: Sign with the API wallet to pay fees and act as the relayer submitter.
    const sig = await connection.sendRawTransaction(tx.serialize()); // WHY: Send the transaction to the cluster.
    await connection.confirmTransaction(sig, "confirmed"); // WHY: Wait for on-chain confirmation before responding.
    res.json({ success: true, signature: sig, messageHash: messageHash.toString("hex") }); // WHY: Return the signature and message hash for client audit.
  } catch (err) { // WHY: Catch errors from missing records, bad signatures, or RPC failures.
    res.status(500).json({ error: String(err) }); // WHY: Return the error as JSON for client debugging.
  } // WHY: Close the try block.
}); // WHY: Close the /mint route handler.

app.post("/burn", async (req, res) => { // WHY: Register an endpoint for users to burn wrapped tokens and request original token release.
  try { // WHY: Open a try block to handle transaction failures gracefully.
    const { userSecretKey, amount } = req.body; // WHY: Extract the user's secret key and burn amount from the request body.
    const userKp = Keypair.fromSecretKey(Uint8Array.from(userSecretKey)); // WHY: Reconstruct the user's keypair to sign the burn transaction.
    const userPubkey = userKp.publicKey; // WHY: Cache the user's public key.
    const bridgeState = getBridgeStatePDA(); // WHY: Derive the bridge state address.
    const wrappedMint = await bridgeProgram.account.bridgeState.fetch(bridgeState).then((s: any) => s.wrappedMint); // WHY: Fetch the wrapped mint from on-chain state.
    const userWrappedAccount = getAssociatedTokenAddressSync(wrappedMint, userPubkey); // WHY: Derive the user's wrapped token account.
    const stateData = await bridgeProgram.account.bridgeState.fetch(bridgeState); // WHY: Fetch the current nonce to derive the burn record PDA.
    const burnRecordSeed = new BN(stateData.nonce.toString()).toArrayLike(Buffer, "le", 8); // WHY: Convert the current nonce to seed bytes.
    const burnRecord = PublicKey.findProgramAddressSync([Buffer.from("burn_record"), burnRecordSeed], bridgeProgramId)[0]; // WHY: Derive the burn record address using the current nonce.
    const tx = await bridgeProgram.methods // WHY: Start building the burn_wrapped instruction.
      .burnWrapped(new BN(amount)) // WHY: Pass the burn amount as a BN.
      .accounts({ // WHY: Map all required accounts.
        user: userPubkey, // WHY: The user must sign because they own the wrapped tokens being destroyed.
        bridgeState, // WHY: Bridge state is needed to read and increment the nonce.
        wrappedMint, // WHY: The wrapped mint account tracks supply reduction.
        userWrappedAccount, // WHY: The source account for the burn.
        burnRecord, // WHY: The new account that stores burn metadata for release verification.
        tokenProgram: TOKEN_PROGRAM_ID, // WHY: SPL Token program executes the burn.
        systemProgram: SystemProgram.programId, // WHY: System program allocates the burn record account.
        rent: SYSVAR_RENT_PUBKEY, // WHY: Rent sysvar calculates exemption for the new account.
      }) // WHY: Close accounts mapping.
      .transaction(); // WHY: Build the transaction object.
    tx.feePayer = wallet.publicKey; // WHY: API wallet pays fees.
    tx.recentBlockhash = (await connection.getLatestBlockhash()).blockhash; // WHY: Fresh blockhash for validity.
    tx.partialSign(userKp); // WHY: User signs to authorize token destruction.
    tx.partialSign(wallet.payer); // WHY: API wallet signs to pay and submit.
    const sig = await connection.sendRawTransaction(tx.serialize()); // WHY: Submit to network.
    await connection.confirmTransaction(sig, "confirmed"); // WHY: Wait for confirmation.
    res.json({ success: true, signature: sig }); // WHY: Return success and signature.
  } catch (err) { // WHY: Catch burn errors.
    res.status(500).json({ error: String(err) }); // WHY: Return error details.
  } // WHY: Close the try block.
}); // WHY: Close the /burn route handler.

app.post("/release", async (req, res) => { // WHY: Register an endpoint that accepts guardian signatures and releases original tokens.
  try { // WHY: Open a try block for release validation and RPC errors.
    const { burnNonce, signatures, guardianIndices } = req.body; // WHY: Extract burn nonce and guardian proof from the request.
    const bridgeState = getBridgeStatePDA(); // WHY: Derive bridge state.
    const burnRecordSeed = new BN(burnNonce).toArrayLike(Buffer, "le", 8); // WHY: Convert nonce to seed bytes.
    const burnRecord = PublicKey.findProgramAddressSync([Buffer.from("burn_record"), burnRecordSeed], bridgeProgramId)[0]; // WHY: Derive the burn record address.
    const burnData = await bridgeProgram.account.burnRecord.fetch(burnRecord); // WHY: Fetch burn details to compute the release message and derive accounts.
    const originalMint = await bridgeProgram.account.bridgeState.fetch(bridgeState).then((s: any) => s.originalMint); // WHY: Fetch the original mint from bridge state.
    const vault = getVaultPDA(bridgeState); // WHY: Derive the vault holding the original tokens.
    const recipientTokenAccount = getAssociatedTokenAddressSync(originalMint, burnData.user); // WHY: Derive the user's original token account to receive released tokens.
    const guardianRegistry = getGuardianRegistryPDA(); // WHY: Derive the guardian registry.
    const message = Buffer.concat([burnData.user.toBuffer(), new BN(burnData.amount.toString()).toArrayLike(Buffer, "le", 8), burnRecordSeed]); // WHY: Reconstruct the exact signed message for verification.
    const messageHash = createHash("sha256").update(message).digest(); // WHY: Compute SHA-256 digest.
    const sigs = signatures.map((s: string) => Uint8Array.from(Buffer.from(s, "base64"))); // WHY: Decode base64 signatures to bytes.
    const indices = guardianIndices.map((i: number) => i); // WHY: Copy indices.
    const tx = await bridgeProgram.methods // WHY: Build release_tokens instruction.
      .releaseTokens(Array.from(messageHash), sigs, indices) // WHY: Pass hash, signatures, and indices.
      .accounts({ // WHY: Map all required accounts.
        bridgeState, // WHY: State for threshold and bumps.
        burnRecord, // WHY: Record to prevent double release.
        vault, // WHY: Source of original tokens.
        recipientTokenAccount, // WHY: Destination for original tokens.
        guardianRegistry, // WHY: Registry for signature verification.
        tokenProgram: TOKEN_PROGRAM_ID, // WHY: SPL Token program for transfer CPI.
      }) // WHY: Close accounts mapping.
      .transaction(); // WHY: Build transaction.
    tx.feePayer = wallet.publicKey; // WHY: API wallet pays fees.
    tx.recentBlockhash = (await connection.getLatestBlockhash()).blockhash; // WHY: Fresh blockhash.
    tx.partialSign(wallet.payer); // WHY: Sign and submit.
    const sig = await connection.sendRawTransaction(tx.serialize()); // WHY: Send to network.
    await connection.confirmTransaction(sig, "confirmed"); // WHY: Confirm.
    res.json({ success: true, signature: sig, messageHash: messageHash.toString("hex") }); // WHY: Respond with proof.
  } catch (err) { // WHY: Catch release errors.
    res.status(500).json({ error: String(err) }); // WHY: Return error details.
  } // WHY: Close the try block.
}); // WHY: Close the /release route handler.

app.post("/guardian/register", async (req, res) => { // WHY: Register an endpoint to add a new guardian to the registry.
  try { // WHY: Handle validation and RPC errors.
    const { guardianAuthoritySecretKey, ed25519Pubkey } = req.body; // WHY: Extract the guardian's Solana authority and their Ed25519 public key.
    const guardianKp = Keypair.fromSecretKey(Uint8Array.from(guardianAuthoritySecretKey)); // WHY: Reconstruct the guardian authority keypair.
    const registry = getGuardianRegistryPDA(); // WHY: Derive the registry address.
    const tx = await guardianProgram.methods // WHY: Build the register_guardian instruction.
      .registerGuardian(Uint8Array.from(Buffer.from(ed25519Pubkey, "hex"))) // WHY: Convert the hex Ed25519 pubkey to bytes for the program.
      .accounts({ // WHY: Map accounts.
        guardianAuthority: guardianKp.publicKey, // WHY: The guardian authority is the signer.
        registry, // WHY: The registry account receives the new guardian entry.
      }) // WHY: Close accounts mapping.
      .transaction(); // WHY: Build transaction.
    tx.feePayer = wallet.publicKey; // WHY: API pays fees.
    tx.recentBlockhash = (await connection.getLatestBlockhash()).blockhash; // WHY: Fresh blockhash.
    tx.partialSign(guardianKp); // WHY: Guardian authority signs to authorize registration.
    tx.partialSign(wallet.payer); // WHY: API wallet signs.
    const sig = await connection.sendRawTransaction(tx.serialize()); // WHY: Send.
    await connection.confirmTransaction(sig, "confirmed"); // WHY: Confirm.
    res.json({ success: true, signature: sig }); // WHY: Respond.
  } catch (err) { // WHY: Catch errors.
    res.status(500).json({ error: String(err) }); // WHY: Return details.
  } // WHY: Close the try block.
}); // WHY: Close the /guardian/register route handler.

app.get("/guardian/list", async (_req, res) => { // WHY: Register an endpoint to return the current guardian registry.
  try { // WHY: Handle fetch errors.
    const registry = getGuardianRegistryPDA(); // WHY: Derive registry address.
    const data = await guardianProgram.account.guardianRegistry.fetch(registry); // WHY: Fetch deserialized registry from chain.
    res.json({ guardians: data.guardians }); // WHY: Return the guardians array as JSON.
  } catch (err) { // WHY: Catch fetch errors.
    res.status(500).json({ error: String(err) }); // WHY: Return error.
  } // WHY: Close the try block.
}); // WHY: Close the /guardian/list route handler.

app.get("/bridge/status/:tx", async (req, res) => { // WHY: Register an endpoint to inspect a transaction or lock/burn record by nonce.
  try { // WHY: Handle lookup errors.
    const { tx } = req.params; // WHY: Extract the transaction signature or nonce identifier from the URL.
    const txInfo = await connection.getTransaction(tx, { commitment: "confirmed" }); // WHY: Attempt to fetch the full transaction metadata from the cluster.
    if (txInfo) { // WHY: If the cluster returns data, respond with transaction details.
      return res.json({ type: "transaction", info: txInfo }); // WHY: Return transaction info and exit to avoid further lookup.
    } // WHY: End signature lookup branch.
    const nonce = parseInt(tx, 10); // WHY: Parse the parameter as an integer nonce.
    const lockRecordSeed = new BN(nonce).toArrayLike(Buffer, "le", 8); // WHY: Convert the nonce to seed bytes.
    const lockRecord = PublicKey.findProgramAddressSync([Buffer.from("lock_record"), lockRecordSeed], bridgeProgramId)[0]; // WHY: Derive the lock record for this nonce.
    try { // WHY: Attempt to fetch the lock record.
      const lockData = await bridgeProgram.account.lockRecord.fetch(lockRecord); // WHY: Fetch the lock record from chain.
      return res.json({ type: "lock", data: lockData }); // WHY: Return lock details if found.
    } catch (_) { // WHY: Ignore lock fetch failure and continue to burn lookup.
    } // WHY: End lock lookup.
    const burnRecord = PublicKey.findProgramAddressSync([Buffer.from("burn_record"), lockRecordSeed], bridgeProgramId)[0]; // WHY: Derive the burn record for this nonce.
    try { // WHY: Attempt to fetch the burn record.
      const burnData = await bridgeProgram.account.burnRecord.fetch(burnRecord); // WHY: Fetch the burn record from chain.
      return res.json({ type: "burn", data: burnData }); // WHY: Return burn details if found.
    } catch (_) { // WHY: Ignore burn fetch failure.
    } // WHY: End burn lookup.
    res.status(404).json({ error: "Not found" }); // WHY: Return 404 if nothing matches the identifier.
  } catch (err) { // WHY: Catch unexpected lookup errors.
    res.status(500).json({ error: String(err) }); // WHY: Return error.
  } // WHY: Close the try block.
}); // WHY: Close the /bridge/status route handler.

const PORT = process.env.PORT || 3065; // WHY: Allow environment override for the API port.
app.listen(PORT, () => { // WHY: Start the HTTP server.
  console.log("Bridge API listening on port " + PORT); // WHY: Log startup so operators know the service is ready.
}); // WHY: Close the listen callback.
