import { Connection, PublicKey, Keypair } from "@solana/web3.js"; // WHY: Solana core types for network interaction
import { AnchorProvider, Program, Wallet, BN } from "@coral-xyz/anchor"; // WHY: Anchor framework for program interaction
import fs from "fs"; // WHY: File system access for IDL and keypair

// WHY: Load program IDL generated by Anchor build
const idl = JSON.parse(fs.readFileSync("./target/idl/farm.json", "utf-8")); // WHY: IDL defines instruction schemas

// WHY: Connect to devnet for monitoring real pools
const connection = new Connection("https://api.devnet.solana.com", "confirmed"); // WHY: Confirmed commitment for reliable reads

// WHY: Load bot operator keypair for signing compound transactions
const botKeypair = Keypair.fromSecretKey( // WHY: Bot needs its own keypair to pay for transactions
    Uint8Array.from(JSON.parse(fs.readFileSync("/Users/zen/.config/solana/id.json", "utf-8"))) // WHY: Standard keypair location
); // WHY: Bot pays transaction fees (subsidized by protocol or user delegation)

// WHY: Create Anchor provider for the bot
const provider = new AnchorProvider( // WHY: Provider required for program interactions
    connection, // WHY: RPC connection
    new Wallet(botKeypair), // WHY: Bot wallet signs compound transactions
    { commitment: "confirmed" } // WHY: Wait for confirmation
); // WHY: Bot operates as a wallet-based client

// WHY: Initialize program instance for building instructions
const program = new Program( // WHY: Typed program interface
    idl, // WHY: Instruction schemas
    new PublicKey("Farm111111111111111111111111111111111111111"), // WHY: Farm program ID
    provider // WHY: Bot provider
); // WHY: Program object for instruction building

// WHY: Configuration for economic rationality and monitoring
const MIN_REWARD_THRESHOLD = new BN(1_000_000); // WHY: 1 token with 6 decimals; must exceed tx cost
const POLL_INTERVAL_MS = 30000; // WHY: 30 seconds between monitoring cycles
const MAX_RETRIES = 3; // WHY: Retry failed transactions up to 3 times
const RETRY_DELAY_MS = 5000; // WHY: 5 seconds between retries

// WHY: In-memory set of whitelisted pools to monitor
// WHY: In production, this would be a database table or on-chain registry
const monitoredPools: PublicKey[] = []; // WHY: Start empty; populated via addPool

// WHY: Helper to derive user info PDA
function deriveUserInfoPDA(pool: PublicKey, user: PublicKey): [PublicKey, number] { // WHY: Same derivation as API
    return PublicKey.findProgramAddressSync( // WHY: Deterministic PDA
        [Buffer.from("user_info"), pool.toBuffer(), user.toBuffer()], // WHY: Match Rust seeds
        program.programId // WHY: Farm program
    ); // WHY: Address for fetching user state
}

// WHY: Helper to derive vault PDAs
function deriveVaultPDAs(pool: PublicKey): { stakeVault: PublicKey; rewardVault: PublicKey } { // WHY: Both vaults needed
    const [stakeVault] = PublicKey.findProgramAddressSync( // WHY: Stake vault
        [Buffer.from("stake_vault"), pool.toBuffer()], // WHY: Seeds
        program.programId // WHY: Program
    ); // WHY: PDA
    const [rewardVault] = PublicKey.findProgramAddressSync( // WHY: Reward vault
        [Buffer.from("reward_vault"), pool.toBuffer()], // WHY: Seeds
        program.programId // WHY: Program
    ); // WHY: PDA
    return { stakeVault, rewardVault }; // WHY: Return both
}

// WHY: Add a pool to the monitoring list
export function addPool(poolAddress: string): void { // WHY: Exported for external configuration
    const poolPubkey = new PublicKey(poolAddress); // WHY: Convert to PublicKey
    monitoredPools.push(poolPubkey); // WHY: Add to monitoring list
    console.log(`Added pool ${poolAddress} to monitoring`); // WHY: Confirm addition
} // WHY: Pool will be checked each polling cycle

// WHY: Calculate pending rewards for a specific user
async function calculatePendingRewards(
    pool: PublicKey, // WHY: Pool address
    user: PublicKey // WHY: User address
): Promise<BN> { // WHY: Return BN for precision
    const [userInfoPDA] = deriveUserInfoPDA(pool, user); // WHY: Derive PDA
    try { // WHY: User may not have staked
        const userInfo = await program.account.userInfo.fetch(userInfoPDA); // WHY: On-chain user state
        const poolAccount = await program.account.pool.fetch(pool); // WHY: On-chain pool state

        // WHY: Simulate time-based accrual since last on-chain update
        const currentTime = Math.floor(Date.now() / 1000); // WHY: Current Unix timestamp in seconds
        const timeDelta = currentTime - poolAccount.lastUpdateTime.toNumber(); // WHY: Seconds since last update
        const timeDeltaBN = new BN(timeDelta); // WHY: BN for safe math

        // WHY: Calculate rewards that have accrued since last update but not yet in accumulator
        let currentRps = new BN(poolAccount.rewardPerShare.toString()); // WHY: Current on-chain accumulator
        if (timeDelta > 0 && poolAccount.totalStaked.toNumber() > 0) { // WHY: Only if time passed and stakers exist
            const rewards = timeDeltaBN // WHY: Seconds
                .mul(new BN(poolAccount.rewardRate.toString())) // WHY: Rate per second
                .mul(new BN("1000000000000000000")) // WHY: PRECISION factor
                .div(new BN(poolAccount.totalStaked.toString())); // WHY: Per-share amount
            currentRps = currentRps.add(rewards); // WHY: Add estimated accrual
        } // WHY: This gives live pending without requiring a transaction

        const staked = new BN(userInfo.stakedAmount); // WHY: User stake
        const debt = new BN(userInfo.rewardDebt.toString()); // WHY: User snapshot
        const accrued = staked.mul(currentRps); // WHY: staked * accumulator
        const pendingRaw = accrued.sub(debt); // WHY: Subtract paid rewards
        const pending = pendingRaw.div(new BN("1000000000000000000")); // WHY: Remove precision

        return pending; // WHY: Return calculated pending rewards
    } catch (error) { // WHY: User may not exist
        return new BN(0); // WHY: No stake means no rewards
    } // WHY: Graceful handling of unstaked users
} // WHY: Calculation complete

// WHY: Build and submit a compound transaction for a user
async function compoundUser(
    pool: PublicKey, // WHY: Pool address
    user: PublicKey, // WHY: User address
    pendingRewards: BN // WHY: Pre-calculated reward amount
): Promise<string | null> { // WHY: Return signature or null
    const [userInfoPDA] = deriveUserInfoPDA(pool, user); // WHY: Derive user info
    const { stakeVault, rewardVault } = deriveVaultPDAs(pool); // WHY: Derive vaults

    const poolAccount = await program.account.pool.fetch(pool); // WHY: Read pool for reward mint

    // WHY: Build compound instruction
    const tx = await program.methods // WHY: Anchor methods
        .compound() // WHY: Atomic claim-and-restake
        .accounts({ // WHY: All accounts
            user: user, // WHY: User address (bot may be authorized delegate)
            pool: pool, // WHY: Pool
            userInfo: userInfoPDA, // WHY: User info PDA
            stakeVault: stakeVault, // WHY: Farm stake vault
            rewardVault: rewardVault, // WHY: Farm reward vault
            rewardMint: poolAccount.rewardMint, // WHY: Reward token mint
            tokenProgram: new PublicKey("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"), // WHY: Token-2022 program ID
        })
        .transaction(); // WHY: Build unsigned transaction

    // WHY: Attempt transaction with retries
    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) { // WHY: Retry loop
        try { // WHY: Each attempt may fail independently
            const signature = await provider.sendAndConfirm(tx); // WHY: Bot signs and pays
            console.log(`Compounded ${pendingRewards.toString()} for ${user.toBase58()}: ${signature}`); // WHY: Log success
            return signature; // WHY: Return transaction signature
        } catch (error) { // WHY: Transaction may fail
            console.error(`Compound attempt ${attempt} failed for ${user.toBase58()}:`, error); // WHY: Log failure
            if (attempt < MAX_RETRIES) { // WHY: Don't delay on last attempt
                await new Promise(resolve => setTimeout(resolve, RETRY_DELAY_MS)); // WHY: Wait before retry
            } // WHY: Exponential backoff could be added here
        } // WHY: Try again
    } // WHY: All retries exhausted

    return null; // WHY: Signal permanent failure after retries
} // WHY: Compound attempt complete

// WHY: Main monitoring function that runs continuously
async function monitorPools(): Promise<void> { // WHY: Async for blockchain calls
    console.log("Starting pool monitoring cycle..."); // WHY: Log cycle start

    for (const pool of monitoredPools) { // WHY: Check each monitored pool
        try { // WHY: Per-pool error isolation
            console.log(`Monitoring pool ${pool.toBase58()}`); // WHY: Log which pool

            // WHY: Fetch all user info accounts for this pool
            const userInfoAccounts = await program.account.userInfo.all([ // WHY: Anchor helper fetches all matching accounts
                {
                    memcmp: { // WHY: Memory comparison filter
                        offset: 8 + 8 + 16, // WHY: Offset to 'pool' field in UserInfo (discriminator + staked + debt)
                        bytes: pool.toBase58(), // WHY: Filter by pool address
                    }, // WHY: Only users in this pool
                }, // WHY: Filter object
            ]); // WHY: Returns all user info accounts for pool

            console.log(`Found ${userInfoAccounts.length} users in pool`); // WHY: Log user count

            for (const account of userInfoAccounts) { // WHY: Check each user
                const user = account.account.owner; // WHY: User wallet address from account data
                const pending = await calculatePendingRewards(pool, user); // WHY: Calculate live pending

                // WHY: Only compound if rewards exceed economic threshold
                if (pending.gte(MIN_REWARD_THRESHOLD)) { // WHY: gte = greater than or equal
                    console.log(`User ${user.toBase58()} has ${pending.toString()} pending rewards - compounding`); // WHY: Log action
                    await compoundUser(pool, user, pending); // WHY: Trigger compound
                } else { // WHY: Below threshold
                    console.log(`User ${user.toBase58()} has ${pending.toString()} pending rewards - below threshold`); // WHY: Log skip
                } // WHY: Economic filter prevents negative-value transactions
            } // WHY: All users checked
        } catch (error) { // WHY: Per-pool error isolation
            console.error(`Error monitoring pool ${pool.toBase58()}:`, error); // WHY: Log error
        } // WHY: Continue to next pool
    } // WHY: All pools checked
} // WHY: Monitoring cycle complete

// WHY: Start the auto-compounding service
async function startCompounder(): Promise<void> { // WHY: Async for initialization
    console.log("Auto-compound bot starting..."); // WHY: Log startup
    console.log(`Bot address: ${botKeypair.publicKey.toBase58()}`); // WHY: Log bot identity
    console.log(`Minimum reward threshold: ${MIN_REWARD_THRESHOLD.toString()}`); // WHY: Log config
    console.log(`Poll interval: ${POLL_INTERVAL_MS}ms`); // WHY: Log config

    // WHY: Run first cycle immediately
    await monitorPools(); // WHY: Don't wait for first interval

    // WHY: Set up recurring monitoring
    setInterval(async () => { // WHY: Run monitoring every POLL_INTERVAL_MS
        await monitorPools(); // WHY: Check all pools and users
    }, POLL_INTERVAL_MS); // WHY: Configurable interval
} // WHY: Service is running

// WHY: Entry point when script is executed directly
if (require.main === module) { // WHY: Only start if not imported as module
    startCompounder().catch(error => { // WHY: Catch startup errors
        console.error("Fatal error starting compounder:", error); // WHY: Log fatal error
        process.exit(1); // WHY: Exit with error code
    }); // WHY: Start service
} // WHY: Entry point complete

// WHY: Export functions for testing and external orchestration
export { startCompounder, monitorPools, calculatePendingRewards, compoundUser }; // WHY: Testable and composable
