import express from "express"; // WHY: Web framework for REST API endpoints
import { Connection, PublicKey, Keypair } from "@solana/web3.js"; // WHY: Solana core types for addresses and transactions
import { AnchorProvider, Program, Wallet, BN } from "@coral-xyz/anchor"; // WHY: Anchor framework for program interaction
import { getAssociatedTokenAddressSync, TOKEN_2022_PROGRAM_ID } from "@solana/spl-token"; // WHY: SPL Token helpers for ATA derivation and program ID
import fs from "fs"; // WHY: File system access for reading keypair and IDL

// WHY: Load program IDL from file system; IDL defines account structures and instruction schemas
const idl = JSON.parse(fs.readFileSync("./target/idl/farm.json", "utf-8")); // WHY: IDL generated by Anchor build

// WHY: Create Express application instance
const app = express(); // WHY: Express handles HTTP routing and middleware
app.use(express.json()); // WHY: Parse JSON request bodies for POST endpoints

// WHY: Connect to Solana devnet for testing with real network conditions
const connection = new Connection("https://api.devnet.solana.com", "confirmed"); // WHY: Confirmed commitment for transaction finality

// WHY: Load payer keypair from standard Solana CLI location for signing transactions
const payerKeypair = Keypair.fromSecretKey( // WHY: Convert secret key bytes to Keypair object
    Uint8Array.from(JSON.parse(fs.readFileSync("/Users/zen/.config/solana/id.json", "utf-8"))) // WHY: Standard CLI keypair file
); // WHY: This keypair pays for account creation and transaction fees

// WHY: Create Anchor provider that links connection, wallet, and confirmation settings
const provider = new AnchorProvider( // WHY: Provider is required for all Anchor program interactions
    connection, // WHY: RPC connection for reading state and sending transactions
    new Wallet(payerKeypair), // WHY: Wallet signs transactions
    { commitment: "confirmed" } // WHY: Wait for confirmation before returning
); // WHY: Provider is the bridge between client and blockchain

// WHY: Initialize Anchor program instance with IDL and program ID
const program = new Program( // WHY: Program object provides typed methods for all instructions
    idl, // WHY: IDL defines method names, accounts, and types
    new PublicKey("Farm111111111111111111111111111111111111111"), // WHY: Farm program ID from deployment
    provider // WHY: Provider handles signing and sending
); // WHY: Typed program interface prevents calling non-existent instructions

// WHY: Helper function to derive Pool PDA from authority address
function derivePoolPDA(authority: PublicKey): [PublicKey, number] { // WHY: Returns address and bump
    return PublicKey.findProgramAddressSync( // WHY: Synchronous derivation for route handlers
        [Buffer.from("pool"), authority.toBuffer()], // WHY: Must match seeds in Rust program
        program.programId // WHY: Farm program ID
    ); // WHY: Deterministic address means no need to store pool address off-chain
}

// WHY: Helper function to derive UserInfo PDA from pool and user addresses
function deriveUserInfoPDA(pool: PublicKey, user: PublicKey): [PublicKey, number] { // WHY: Returns address and bump
    return PublicKey.findProgramAddressSync( // WHY: Synchronous derivation
        [Buffer.from("user_info"), pool.toBuffer(), user.toBuffer()], // WHY: Must match Rust seeds
        program.programId // WHY: Farm program ID
    ); // WHY: Deterministic address per user per pool
}

// WHY: Helper function to derive vault PDAs from pool address
function deriveVaultPDAs(pool: PublicKey): { stakeVault: PublicKey; rewardVault: PublicKey } { // WHY: Return both vaults
    const [stakeVault] = PublicKey.findProgramAddressSync( // WHY: Stake vault PDA
        [Buffer.from("stake_vault"), pool.toBuffer()], // WHY: Seeds from Rust
        program.programId // WHY: Farm program
    ); // WHY: PDA holding staked tokens
    const [rewardVault] = PublicKey.findProgramAddressSync( // WHY: Reward vault PDA
        [Buffer.from("reward_vault"), pool.toBuffer()], // WHY: Seeds from Rust
        program.programId // WHY: Farm program
    ); // WHY: PDA holding reward tokens
    return { stakeVault, rewardVault }; // WHY: Object with both addresses
}

// WHY: POST /pool/create - Initialize a new farm pool with stake and reward tokens
app.post("/pool/create", async (req, res) => { // WHY: Async because blockchain calls are promises
    try { // WHY: Catch errors to prevent server crash and return meaningful HTTP status
        const { stakeMint, rewardMint, rewardRate } = req.body; // WHY: Destructure request parameters

        // WHY: Validate inputs to prevent invalid transactions
        if (!stakeMint || !rewardMint || !rewardRate) { // WHY: All fields required
            return res.status(400).json({ error: "Missing required fields" }); // WHY: 400 Bad Request
        } // WHY: Early validation saves RPC calls

        const stakeMintPubkey = new PublicKey(stakeMint); // WHY: Convert string to PublicKey
        const rewardMintPubkey = new PublicKey(rewardMint); // WHY: Convert string to PublicKey
        const authority = payerKeypair.publicKey; // WHY: Admin is the API operator

        const [poolPDA] = derivePoolPDA(authority); // WHY: Derive pool address
        const { stakeVault, rewardVault } = deriveVaultPDAs(poolPDA); // WHY: Derive vault addresses

        // WHY: Build create_pool transaction using Anchor
        const tx = await program.methods // WHY: Anchor methods object for typed instruction building
            .createPool(new BN(rewardRate)) // WHY: BN handles u64 values that exceed JavaScript safe integer range
            .accounts({ // WHY: Explicitly list all accounts required by instruction
                authority: authority, // WHY: Admin signer
                pool: poolPDA, // WHY: Pool PDA
                stakeMint: stakeMintPubkey, // WHY: Stake token mint
                rewardMint: rewardMintPubkey, // WHY: Reward token mint
                stakeVault: stakeVault, // WHY: Stake vault PDA
                rewardVault: rewardVault, // WHY: Reward vault PDA
                tokenProgram: TOKEN_2022_PROGRAM_ID, // WHY: Token-2022 program
                systemProgram: PublicKey.default, // WHY: System program for account creation
                rent: PublicKey.default, // WHY: Rent sysvar (Anchor handles actual address)
            })
            .transaction(); // WHY: Build unsigned transaction object

        // WHY: Sign and send transaction
        const signature = await provider.sendAndConfirm(tx); // WHY: Provider signs with payer wallet

        return res.json({ // WHY: Return success response
            success: true, // WHY: Client knows transaction succeeded
            pool: poolPDA.toBase58(), // WHY: Human-readable pool address
            signature // WHY: Transaction signature for Solana explorer
        }); // WHY: JSON response for API consumers
    } catch (error) { // WHY: Catch all errors
        console.error("Pool creation error:", error); // WHY: Log server-side for debugging
        return res.status(500).json({ error: String(error) }); // WHY: 500 Internal Server Error
    } // WHY: Always return response to prevent hanging connection
}); // WHY: Route handler complete

// WHY: POST /stake - Stake tokens into a pool
app.post("/stake", async (req, res) => { // WHY: Async for blockchain calls
    try { // WHY: Error handling
        const { pool, user, amount } = req.body; // WHY: Extract parameters

        if (!pool || !user || !amount) { // WHY: Validate all required fields
            return res.status(400).json({ error: "Missing required fields" }); // WHY: Bad request
        } // WHY: Prevent invalid transactions

        const poolPubkey = new PublicKey(pool); // WHY: Convert to PublicKey
        const userPubkey = new PublicKey(user); // WHY: Convert to PublicKey
        const amountBN = new BN(amount); // WHY: BN for large numbers

        const [userInfoPDA] = deriveUserInfoPDA(poolPubkey, userPubkey); // WHY: Derive user info address
        const { stakeVault } = deriveVaultPDAs(poolPubkey); // WHY: Derive stake vault

        // WHY: Derive user's ATA for stake tokens
        const userStakeAccount = getAssociatedTokenAddressSync( // WHY: Deterministic ATA address
            (await connection.getAccountInfo(poolPubkey))!.owner, // WHY: This is wrong, should use stake mint from pool
            userPubkey, // WHY: Token owner
            false, // WHY: Not allow owner off curve
            TOKEN_2022_PROGRAM_ID // WHY: Token-2022 program
        ); // WHY: User's token account

        // WHY: Fetch pool to get stake mint (proper implementation)
        const poolAccount = await program.account.pool.fetch(poolPubkey); // WHY: Read on-chain pool state
        const correctUserStakeAccount = getAssociatedTokenAddressSync( // WHY: Re-derive with correct mint
            poolAccount.stakeMint, // WHY: Actual stake mint from pool
            userPubkey, // WHY: Token owner
            false, // WHY: Standard ATA
            TOKEN_2022_PROGRAM_ID // WHY: Token-2022 program
        ); // WHY: Correct ATA address

        // WHY: Build stake transaction
        const tx = await program.methods // WHY: Anchor methods
            .stake(amountBN) // WHY: Stake amount as BN
            .accounts({ // WHY: All accounts for instruction
                user: userPubkey, // WHY: Staker signer
                pool: poolPubkey, // WHY: Target pool
                userInfo: userInfoPDA, // WHY: User info PDA
                userStakeAccount: correctUserStakeAccount, // WHY: User's token account
                stakeVault: stakeVault, // WHY: Farm vault
                stakeMint: poolAccount.stakeMint, // WHY: For decimal validation
                tokenProgram: TOKEN_2022_PROGRAM_ID, // WHY: Token-2022 program
                systemProgram: PublicKey.default, // WHY: System program
                rent: PublicKey.default, // WHY: Rent sysvar
            })
            .transaction(); // WHY: Build unsigned transaction

        // WHY: IMPORTANT: User must sign this transaction with their wallet
        // WHY: This API returns an unsigned transaction for frontend signing
        const serializedTx = tx.serialize({ requireAllSignatures: false }); // WHY: Allow partial signatures
        const base64Tx = Buffer.from(serializedTx).toString("base64"); // WHY: Base64 for JSON transport

        return res.json({ // WHY: Return transaction for user signing
            success: true, // WHY: Transaction built successfully
            transaction: base64Tx, // WHY: User signs this in their wallet
            userInfo: userInfoPDA.toBase58() // WHY: User info address for reference
        }); // WHY: Frontend deserializes and signs with user wallet
    } catch (error) { // WHY: Error handling
        console.error("Stake error:", error); // WHY: Server logging
        return res.status(500).json({ error: String(error) }); // WHY: Server error
    } // WHY: Always respond
}); // WHY: Route complete

// WHY: POST /unstake - Withdraw staked tokens and claim rewards
app.post("/unstake", async (req, res) => { // WHY: Async for blockchain
    try { // WHY: Error handling
        const { pool, user, amount } = req.body; // WHY: Extract parameters

        if (!pool || !user || !amount) { // WHY: Validation
            return res.status(400).json({ error: "Missing required fields" }); // WHY: Bad request
        } // WHY: Prevent errors

        const poolPubkey = new PublicKey(pool); // WHY: Convert to PublicKey
        const userPubkey = new PublicKey(user); // WHY: Convert to PublicKey
        const amountBN = new BN(amount); // WHY: BN for large numbers

        const [userInfoPDA] = deriveUserInfoPDA(poolPubkey, userPubkey); // WHY: Derive user info
        const { stakeVault, rewardVault } = deriveVaultPDAs(poolPubkey); // WHY: Derive both vaults

        const poolAccount = await program.account.pool.fetch(poolPubkey); // WHY: Read pool state

        // WHY: Derive user's ATAs
        const userStakeAccount = getAssociatedTokenAddressSync( // WHY: User's stake ATA
            poolAccount.stakeMint, // WHY: Stake mint
            userPubkey, // WHY: Owner
            false, // WHY: Standard
            TOKEN_2022_PROGRAM_ID // WHY: Token-2022
        ); // WHY: Stake token wallet
        const userRewardAccount = getAssociatedTokenAddressSync( // WHY: User's reward ATA
            poolAccount.rewardMint, // WHY: Reward mint
            userPubkey, // WHY: Owner
            false, // WHY: Standard
            TOKEN_2022_PROGRAM_ID // WHY: Token-2022
        ); // WHY: Reward token wallet

        // WHY: Build unstake transaction
        const tx = await program.methods // WHY: Anchor methods
            .unstake(amountBN) // WHY: Unstake amount
            .accounts({ // WHY: All accounts
                user: userPubkey, // WHY: Signer
                pool: poolPubkey, // WHY: Pool
                userInfo: userInfoPDA, // WHY: User info
                userStakeAccount: userStakeAccount, // WHY: User stake wallet
                userRewardAccount: userRewardAccount, // WHY: User reward wallet
                stakeVault: stakeVault, // WHY: Farm stake vault
                rewardVault: rewardVault, // WHY: Farm reward vault
                stakeMint: poolAccount.stakeMint, // WHY: For validation
                rewardMint: poolAccount.rewardMint, // WHY: For validation
                tokenProgram: TOKEN_2022_PROGRAM_ID, // WHY: Token-2022 program
            })
            .transaction(); // WHY: Build unsigned transaction

        const serializedTx = tx.serialize({ requireAllSignatures: false }); // WHY: Partial signatures
        const base64Tx = Buffer.from(serializedTx).toString("base64"); // WHY: Base64 encoding

        return res.json({ // WHY: Return for user signing
            success: true, // WHY: Built successfully
            transaction: base64Tx // WHY: User signs this
        }); // WHY: Frontend handles signing
    } catch (error) { // WHY: Error handling
        console.error("Unstake error:", error); // WHY: Server log
        return res.status(500).json({ error: String(error) }); // WHY: Server error
    } // WHY: Always respond
}); // WHY: Route complete

// WHY: POST /claim - Claim accumulated rewards without unstaking
app.post("/claim", async (req, res) => { // WHY: Async for blockchain
    try { // WHY: Error handling
        const { pool, user } = req.body; // WHY: Extract parameters

        if (!pool || !user) { // WHY: Validation
            return res.status(400).json({ error: "Missing required fields" }); // WHY: Bad request
        } // WHY: Prevent errors

        const poolPubkey = new PublicKey(pool); // WHY: Convert to PublicKey
        const userPubkey = new PublicKey(user); // WHY: Convert to PublicKey

        const [userInfoPDA] = deriveUserInfoPDA(poolPubkey, userPubkey); // WHY: Derive user info
        const { rewardVault } = deriveVaultPDAs(poolPubkey); // WHY: Derive reward vault

        const poolAccount = await program.account.pool.fetch(poolPubkey); // WHY: Read pool state

        const userRewardAccount = getAssociatedTokenAddressSync( // WHY: User's reward ATA
            poolAccount.rewardMint, // WHY: Reward mint
            userPubkey, // WHY: Owner
            false, // WHY: Standard
            TOKEN_2022_PROGRAM_ID // WHY: Token-2022
        ); // WHY: Reward wallet

        // WHY: Build claim transaction
        const tx = await program.methods // WHY: Anchor methods
            .claim() // WHY: No arguments needed; amount calculated on-chain
            .accounts({ // WHY: All accounts
                user: userPubkey, // WHY: Signer
                pool: poolPubkey, // WHY: Pool
                userInfo: userInfoPDA, // WHY: User info
                userRewardAccount: userRewardAccount, // WHY: User reward wallet
                rewardVault: rewardVault, // WHY: Farm reward vault
                rewardMint: poolAccount.rewardMint, // WHY: For validation
                tokenProgram: TOKEN_2022_PROGRAM_ID, // WHY: Token-2022 program
            })
            .transaction(); // WHY: Build unsigned transaction

        const serializedTx = tx.serialize({ requireAllSignatures: false }); // WHY: Partial signatures
        const base64Tx = Buffer.from(serializedTx).toString("base64"); // WHY: Base64 encoding

        return res.json({ // WHY: Return for signing
            success: true, // WHY: Built successfully
            transaction: base64Tx // WHY: User signs
        }); // WHY: Frontend signs
    } catch (error) { // WHY: Error handling
        console.error("Claim error:", error); // WHY: Server log
        return res.status(500).json({ error: String(error) }); // WHY: Server error
    } // WHY: Always respond
}); // WHY: Route complete

// WHY: POST /compound - Claim and restake rewards in one transaction
app.post("/compound", async (req, res) => { // WHY: Async for blockchain
    try { // WHY: Error handling
        const { pool, user } = req.body; // WHY: Extract parameters

        if (!pool || !user) { // WHY: Validation
            return res.status(400).json({ error: "Missing required fields" }); // WHY: Bad request
        } // WHY: Prevent errors

        const poolPubkey = new PublicKey(pool); // WHY: Convert to PublicKey
        const userPubkey = new PublicKey(user); // WHY: Convert to PublicKey

        const [userInfoPDA] = deriveUserInfoPDA(poolPubkey, userPubkey); // WHY: Derive user info
        const { stakeVault, rewardVault } = deriveVaultPDAs(poolPubkey); // WHY: Derive vaults

        // WHY: Build compound transaction
        const tx = await program.methods // WHY: Anchor methods
            .compound() // WHY: No arguments; amount calculated on-chain
            .accounts({ // WHY: All accounts
                user: userPubkey, // WHY: Signer
                pool: poolPubkey, // WHY: Pool
                userInfo: userInfoPDA, // WHY: User info
                stakeVault: stakeVault, // WHY: Farm stake vault
                rewardVault: rewardVault, // WHY: Farm reward vault
                rewardMint: poolPubkey, // WHY: This is wrong, should fetch pool
                tokenProgram: TOKEN_2022_PROGRAM_ID, // WHY: Token-2022 program
            })
            .transaction(); // WHY: Build unsigned transaction

        // WHY: Fetch pool to fix reward mint (proper implementation)
        const poolAccount = await program.account.pool.fetch(poolPubkey); // WHY: Read pool state

        const txFixed = await program.methods // WHY: Rebuild with correct accounts
            .compound() // WHY: Compound instruction
            .accounts({ // WHY: Correct accounts
                user: userPubkey, // WHY: Signer
                pool: poolPubkey, // WHY: Pool
                userInfo: userInfoPDA, // WHY: User info
                stakeVault: stakeVault, // WHY: Farm stake vault
                rewardVault: rewardVault, // WHY: Farm reward vault
                rewardMint: poolAccount.rewardMint, // WHY: Correct reward mint
                tokenProgram: TOKEN_2022_PROGRAM_ID, // WHY: Token-2022 program
            })
            .transaction(); // WHY: Build correct unsigned transaction

        const serializedTx = txFixed.serialize({ requireAllSignatures: false }); // WHY: Partial signatures
        const base64Tx = Buffer.from(serializedTx).toString("base64"); // WHY: Base64 encoding

        return res.json({ // WHY: Return for signing
            success: true, // WHY: Built successfully
            transaction: base64Tx // WHY: User or bot signs
        }); // WHY: Frontend or service signs
    } catch (error) { // WHY: Error handling
        console.error("Compound error:", error); // WHY: Server log
        return res.status(500).json({ error: String(error) }); // WHY: Server error
    } // WHY: Always respond
}); // WHY: Route complete

// WHY: GET /rewards/:user - Calculate pending rewards for a user without claiming
app.get("/rewards/:user", async (req, res) => { // WHY: Async for blockchain read
    try { // WHY: Error handling
        const { user } = req.params; // WHY: Extract user from URL path
        const { pool } = req.query; // WHY: Extract pool from query string

        if (!pool) { // WHY: Pool required for calculation
            return res.status(400).json({ error: "Pool query parameter required" }); // WHY: Bad request
        } // WHY: Prevent errors

        const userPubkey = new PublicKey(user); // WHY: Convert to PublicKey
        const poolPubkey = new PublicKey(pool as string); // WHY: Convert query string to PublicKey

        const [userInfoPDA] = deriveUserInfoPDA(poolPubkey, userPubkey); // WHY: Derive user info

        // WHY: Fetch user info and pool state from chain
        const userInfo = await program.account.userInfo.fetch(userInfoPDA); // WHY: On-chain user state
        const poolAccount = await program.account.pool.fetch(poolPubkey); // WHY: On-chain pool state

        // WHY: Calculate pending rewards using same math as on-chain program
        const staked = new BN(userInfo.stakedAmount); // WHY: User's stake as BN
        const rps = new BN(poolAccount.rewardPerShare.toString()); // WHY: Global accumulator as BN
        const debt = new BN(userInfo.rewardDebt.toString()); // WHY: User's snapshot as BN

        // WHY: pending = (staked * rps) / PRECISION - debt / PRECISION
        const PRECISION_BN = new BN("1000000000000000000"); // WHY: 1e18 precision factor
        const accrued = staked.mul(rps); // WHY: staked * reward_per_share
        const pendingRaw = accrued.sub(debt); // WHY: Subtract already-paid rewards
        const pending = pendingRaw.div(PRECISION_BN); // WHY: Remove precision factor

        return res.json({ // WHY: Return calculation results
            success: true, // WHY: Request succeeded
            user: userPubkey.toBase58(), // WHY: Human-readable user address
            pool: poolPubkey.toBase58(), // WHY: Human-readable pool address
            stakedAmount: userInfo.stakedAmount.toString(), // WHY: User's current stake as string
            rewardPerShare: poolAccount.rewardPerShare.toString(), // WHY: Global accumulator
            rewardDebt: userInfo.rewardDebt.toString(), // WHY: User's snapshot
            pendingRewards: pending.toString(), // WHY: Calculated pending rewards
        }); // WHY: Frontend displays this without signing transaction
    } catch (error) { // WHY: Error handling
        console.error("Rewards query error:", error); // WHY: Server log
        return res.status(500).json({ error: String(error) }); // WHY: Server error
    } // WHY: Always respond
}); // WHY: Route complete

// WHY: Start Express server on port 3064
const PORT = 3064; // WHY: Dedicated port for Phase 55v2 farm API
app.listen(PORT, () => { // WHY: Bind to port and start accepting connections
    console.log(`Farm API listening on port ${PORT}`); // WHY: Confirm server startup
}); // WHY: Server is running and ready for requests
