#!/bin/bash

# WHY: set -e causes the script to exit immediately if any command fails, preventing partial or broken deployments.
set -e

# WHY: Define colors for readable terminal output so build status is visually distinct.
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# WHY: Print a banner so operators know which phase is being deployed.
echo "========================================"
echo "  Phase 55: Yield Farm Deployment"
echo "========================================"

# ---------------------------------------------------------------------------
# Step 1: Environment Validation
# ---------------------------------------------------------------------------

# WHY: Verify that Solana CLI is installed and available; without it we cannot deploy.
if ! command -v solana &> /dev/null
then
    echo -e "${RED}ERROR: solana CLI not found. Install it first.${NC}"
    exit 1
fi

# WHY: Verify that cargo is installed because Solana programs are Rust binaries built with cargo.
if ! command -v cargo &> /dev/null
then
    echo -e "${RED}ERROR: cargo not found. Install Rust first.${NC}"
    exit 1
fi

# WHY: Confirm the network configuration so we do not accidentally deploy to mainnet.
echo "Current Solana cluster:"
solana config get

# ---------------------------------------------------------------------------
# Step 2: Build Farm Program
# ---------------------------------------------------------------------------

echo ""
echo "Step 1: Building farm program..."

# WHY: cd into the farm program directory so cargo builds the correct package.
cd "$(dirname "$0")/farm"

# WHY: cargo build-bpf compiles the Rust source into a Solana BPF bytecode binary (.so file).
cargo build-bpf

# WHY: Verify the build artifact exists before attempting deployment.
FARM_SO="../target/deploy/phase55_farm.so"
if [ ! -f "$FARM_SO" ]; then
    echo -e "${RED}ERROR: Farm program build artifact not found at $FARM_SO${NC}"
    exit 1
fi

echo -e "${GREEN}Farm program built successfully.${NC}"

# ---------------------------------------------------------------------------
# Step 3: Build Boost Program
# ---------------------------------------------------------------------------

echo ""
echo "Step 2: Building boost program..."

# WHY: cd into the boost program directory for the same reason as above.
cd "$(dirname "$0")/boost"

cargo build-bpf

# WHY: Verify the boost build artifact exists.
BOOST_SO="../target/deploy/phase55_boost.so"
if [ ! -f "$BOOST_SO" ]; then
    echo -e "${RED}ERROR: Boost program build artifact not found at $BOOST_SO${NC}"
    exit 1
fi

echo -e "${GREEN}Boost program built successfully.${NC}"

# ---------------------------------------------------------------------------
# Step 4: Deploy Farm Program
# ---------------------------------------------------------------------------

echo ""
echo "Step 3: Deploying farm program..."

# WHY: solana program deploy uploads the .so binary to the cluster and returns a program ID.
FARM_PROGRAM_ID=$(solana program deploy "$FARM_SO" --output json | grep '"programId"' | sed 's/.*: "\([^"]*\)".*/\1/')

# WHY: Validate that we extracted a program ID; if empty, deployment likely failed silently.
if [ -z "$FARM_PROGRAM_ID" ]; then
    echo -e "${RED}ERROR: Failed to extract farm program ID.${NC}"
    exit 1
fi

echo -e "${GREEN}Farm program deployed: $FARM_PROGRAM_ID${NC}"

# ---------------------------------------------------------------------------
# Step 5: Deploy Boost Program
# ---------------------------------------------------------------------------

echo ""
echo "Step 4: Deploying boost program..."

BOOST_PROGRAM_ID=$(solana program deploy "$BOOST_SO" --output json | grep '"programId"' | sed 's/.*: "\([^"]*\)".*/\1/')

if [ -z "$BOOST_PROGRAM_ID" ]; then
    echo -e "${RED}ERROR: Failed to extract boost program ID.${NC}"
    exit 1
fi

echo -e "${GREEN}Boost program deployed: $BOOST_PROGRAM_ID${NC}"

# ---------------------------------------------------------------------------
# Step 6: Write Environment File
# ---------------------------------------------------------------------------

echo ""
echo "Step 5: Writing .env file..."

# WHY: Write deployed program IDs to .env so the API and compounder can reference them without hardcoding.
cat > "$(dirname "$0")/.env" <<EOF
# WHY: Auto-generated by deploy.sh. Contains deployed program IDs for Phase 55.
SOLANA_RPC_URL=$(solana config get json_rpc_url | awk '{print $2}')
FARM_PROGRAM_ID=$FARM_PROGRAM_ID
BOOST_PROGRAM_ID=$BOOST_PROGRAM_ID
COMPOUND_INTERVAL_MS=300000
REWARD_THRESHOLD=1000000
FEE_PERCENT_BPS=500
EOF

echo -e "${GREEN}.env file written.${NC}"

# ---------------------------------------------------------------------------
# Step 7: Verification
# ---------------------------------------------------------------------------

echo ""
echo "Step 6: Verifying deployments..."

# WHY: solana program show confirms the program is live and returns its details.
solana program show "$FARM_PROGRAM_ID"
solana program show "$BOOST_PROGRAM_ID"

echo ""
echo -e "${GREEN}Phase 55 deployment complete!${NC}"
echo "Farm Program ID: $FARM_PROGRAM_ID"
echo "Boost Program ID: $BOOST_PROGRAM_ID"
echo "Environment written to: $(dirname "$0")/.env"
