[features]
seeds = false
skip-lint = false

[programs.localnet]
secure = "Hpy8x4n4vD8VLDx3v7b7j8k9L0m1n2o3p4q5r6s7t8u9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
